from catalog import db
from catalog.models import Catagory

db.create_all()

animal = Catagory(name='Animal')
db.session.add(animal)
art = Catagory(name='Art')
db.session.add(art)
audio = Catagory(name='Audio')
db.session.add(audio)
autobiograph = Catagory(name='Autobiography')
db.session.add(autobiograph)
biography = Catagory(name='Biography')
db.session.add(biography)
business = Catagory(name='Business')
db.session.add(business)
children = Catagory(name='Children')
db.session.add(children)
classics = Catagory(name='Classics')
db.session.add(classics)
comedy = Catagory(name='Comedy')
db.session.add(comedy)
comic = Catagory(name='Comic')
db.session.add(comic)
computing = Catagory(name='Computing')
db.session.add(computing)
culture = Catagory(name='Culture')
db.session.add(culture)
education = Catagory(name='Education')
db.session.add(education)
fantasy = Catagory(name='Fantasy')
db.session.add(fantasy)
fiction = Catagory(name='Fiction')
db.session.add(fiction)
finance = Catagory(name='Finance')
db.session.add(finance)
food = Catagory(name='Food')
db.session.add(food)
health = Catagory(name='Health')
db.session.add(health)
history = Catagory(name='History')
db.session.add(history)
home = Catagory(name='Home')
db.session.add(home)
horror = Catagory(name='Horror')
db.session.add(horror)
language = Catagory(name='Language')
db.session.add(language)
music = Catagory(name='Music')
db.session.add(music)
nonfiction = Catagory(name='Non-Fiction')
db.session.add(nonfiction)
other = Catagory(name='Other')
db.session.add(other)
poetry = Catagory(name='Poetry')
db.session.add(poetry)
politics = Catagory(name='Politics')
db.session.add(politics)
reference = Catagory(name='Reference')
db.session.add(reference)
religion = Catagory(name='Religion')
db.session.add(religion)
romance = Catagory(name='Romance')
db.session.add(romance)
short = Catagory(name='Short Stories')
db.session.add(short)
sport = Catagory(name='Sport')
db.session.add(sport)
thriller = Catagory(name='Thriller')
db.session.add(thriller)
travel = Catagory(name='Travel')
db.session.add(travel)
true_crime = Catagory(name='True Crime')
db.session.add(true_crime)
db.session.commit()